name: Generate ASCII workflow
on: 
  push:
    
jobs:
    first_job:
      
      runs-on: ubuntu-latest

      steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install cowsay programm
        run: sudo apt-get install -y cowsay

      - name: Execute cowsay cmd command
        run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

      - name: Read files
        run: cat dragon.txt
      