name: Generate ASCII workflow
on: 
  push:
    
jobs:
    first_job:
      
      runs-on: ubuntu-latest

      steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Running the script
        run: |
            chmod u+x script.sh
            ./script.sh
      