name: Generate ASCII multiple jobs workflow
on: 
  push:
    
jobs:
    Job1:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4.2.2

        - name: Install cowsay programm
          run: sudo apt-get install -y cowsay

        - name: Execute cowsay cmd command
          run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

        - name: Sleep for 10s
          run: sleep 10
    
    Job2:
        runs-on: ubuntu-latest
        needs: Job1
        steps:
        - name: Sleep for 10s
          run: sleep 10
        - name: Test file exists
          run: grep -i "dragon" dragon.txt

    Job3:
        runs-on: ubuntu-latest
        needs: Job2
        steps:
        - name: Read file
          run: cat dragon.txt
      