name: Github Action with Teams integration

on: 
  push:

jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install cowsay program
        run: sudo apt-get install -y cowsay

      - name: Execute cowsay cmd command
        run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

      - name: Upload dragon.txt file
        uses: actions/upload-artifact@v4
        with:
          name: dragon.txt file
          path: dragon.txt

  Job2:
    runs-on: ubuntu-latest
    needs: Job1
    steps:
      - name: Download dragon.txt
        uses: actions/download-artifact@v4
        with:
          name: dragon.txt file

      - name: Test file exists
        run: grep -i "dragon" dragon.txt

  Job3:
    runs-on: ubuntu-latest
    needs: Job2
    environment:
      name: production
    steps:
      - name: Notify Teams - Awaiting Manual Approval
        run: |
          curl -H 'Content-Type: application/json' \
          -d "{\"text\": \"🟡 *Manual Approval Required*: Job3 is waiting for *production* approval on commit \`${{ github.sha }}\` in branch \`${{ github.ref_name }}\`\"}" \
          ${{ secrets.TEAMS_WEBHOOK_URL }}

      - name: Download dragon.txt
        uses: actions/download-artifact@v4
        with:
          name: dragon.txt file

      - name: Read file
        run: cat dragon.txt

      - name: Notify Teams - Production Done
        if: always()
        run: |
          STATUS="${{ job.status }}"
          COLOR="🟢"
          if [[ "$STATUS" == "failure" ]]; then COLOR="🔴"; fi
          curl -H 'Content-Type: application/json' \
          -d "{\"text\": \"${COLOR} *Production Complete*: Job3 finished with status: *${STATUS}* on commit \`${{ github.sha }}\` in branch \`${{ github.ref_name }}\`\"}" \
          ${{ secrets.TEAMS_WEBHOOK_URL }}
